# -*- coding: utf-8 -*-
"""Finetune a Generative AI Model

Automatically generated by Colab.


# 1. Dataset Building
"""

from google.colab import drive
drive.mount('/content/drive')

dir = '/content/drive/MyDrive/Dataset'
downloader.download(query="fruit", limit=100, adult_filter_off=True, output_dir=dir)

data_dir = '/content/drive/MyDrive/Dataset/'
sub_dir = data_dir + 'fruit/'
fig = plt.figure(figsize=(8, 5))


image_list = glob.glob(sub_dir + '*')
rows, columns = 2, 3
for num in range(1, rows*columns+1):
    fig.add_subplot(rows, columns, num)
    idx = num - 1
    value = cv2.imread(image_list[idx])
    plt.imshow(cv2.cvtColor(value, cv2.COLOR_BGR2RGB))
fig.tight_layout()

from huggingface_hub import notebook_login
notebook_login()

from datasets import load_dataset
dataset = load_dataset("imagefolder", data_dir="/content/drive/MyDrive/Dataset/fruit",drop_labels=True)
dataset.push_to_hub("Sunanda-Das/fruits-dataset")

"""# 2. Finetune a Foundation Model"""

!pip install diffusers
!pip install accelerate
!pip install git+https://github.com/huggingface/diffusers -q
!pip install accelerate -q
!pip install peft -q
!pip install datasets -q

from diffusers import StableDiffusionPipeline
import torch
from accelerate.utils import write_basic_config
write_basic_config()

!nvidia-smi

def display_images(images, title):
    plt.figure()
    f, axix = plt.subplots(1, len(images), figsize=(20,10))
    for ax, img in zip(axix.flatten(), images):
        ax.imshow(img)
        ax.axis('off')
    plt.title(title)
    plt.show()

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photograph of fruits in a tree"
images = pipe(prompt, num_images_per_prompt=4).images
display_images(images, "Generated Samples from the Base Model")

import requests
file_url = "https://raw.githubusercontent.com/huggingface/diffusers/main/examples/dreambooth/train_dreambooth_lora.py"
response = requests.get(file_url)
with open("train_dreambooth_lora.py", "w") as file:
    file.write(response.text)

MODEL_NAME="runwayml/stable-diffusion-v1-5"
INSTANCE_DIR="/content/drive/MyDrive/Dataset/fruit"
OUTPUT_DIR="/content/"

!accelerate launch train_dreambooth_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of fruits" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --checkpointing_steps=100 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="a photo of fruits" \
  --validation_epochs=50 \
  --seed="0"

from diffusers import AutoPipelineForText2Image
pipeline2 = AutoPipelineForText2Image.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipeline2.load_lora_weights("/content/", weight_name="pytorch_lora_weights.safetensors")

prompt = "a photograph of fruits in a tree"
images_finetuned = pipeline2(prompt, num_images_per_prompt=4).images
display_images(images_finetuned, "Generated Samples from the Fine-tuned Model")
